// countries.ts
export const countries = [
  { name: "Aruba", code: "AW", callSign: "+297" },
  { name: "Afghanistan", code: "AF", callSign: "+93" },
  { name: "Angola", code: "AO", callSign: "+244" },
  { name: "Anguilla", code: "AI", callSign: "+1 264" },
  { name: "Åland Islands", code: "AX", callSign: "+358" },
  { name: "Albania", code: "AL", callSign: "+355" },
  { name: "Andorra", code: "AD", callSign: "+376" },
  { name: "United Arab Emirates", code: "AE", callSign: "+971" },
  { name: "Argentina", code: "AR", callSign: "+54" },
  { name: "Armenia", code: "AM", callSign: "+374" },
  { name: "American Samoa", code: "AS", callSign: "+1 684" },
  { name: "Antarctica", code: "AQ", callSign: "+672" },
  { name: "French Southern Territories", code: "TF", callSign: "+262" },
  { name: "Antigua and Barbuda", code: "AG", callSign: "+1 268" },
  { name: "Australia", code: "AU", callSign: "+61" },
  { name: "Austria", code: "AT", callSign: "+43" },
  { name: "Azerbaijan", code: "AZ", callSign: "+994" },
  { name: "Burundi", code: "BI", callSign: "+257" },
  { name: "Belgium", code: "BE", callSign: "+32" },
  { name: "Benin", code: "BJ", callSign: "+229" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", callSign: "+599" },
  { name: "Burkina Faso", code: "BF", callSign: "+226" },
  { name: "Bangladesh", code: "BD", callSign: "+880" },
  { name: "Bulgaria", code: "BG", callSign: "+359" },
  { name: "Bahrain", code: "BH", callSign: "+973" },
  { name: "Bahamas", code: "BS", callSign: "+1 242" },
  { name: "Bosnia and Herzegovina", code: "BA", callSign: "+387" },
  { name: "Saint Barthélemy", code: "BL", callSign: "+590" },
  { name: "Belarus", code: "BY", callSign: "+375" },
  { name: "Belize", code: "BZ", callSign: "+501" },
  { name: "Bermuda", code: "BM", callSign: "+1 441" },
  { name: "Bolivia", code: "BO", callSign: "+591" },
  { name: "Brazil", code: "BR", callSign: "+55" },
  { name: "Barbados", code: "BB", callSign: "+1 246" },
  { name: "Brunei Darussalam", code: "BN", callSign: "+673" },
  { name: "Bhutan", code: "BT", callSign: "+975" },
  { name: "Bouvet Island", code: "BV", callSign: "+47" },
  { name: "Botswana", code: "BW", callSign: "+267" },
  { name: "Central African Republic", code: "CF", callSign: "+236" },
  { name: "Canada", code: "CA", callSign: "+1" },
  { name: "Cocos (Keeling) Islands", code: "CC", callSign: "+61" },
  { name: "Switzerland", code: "CH", callSign: "+41" },
  { name: "Chile", code: "CL", callSign: "+56" },
  { name: "China", code: "CN", callSign: "+86" },
  { name: "Côte d'Ivoire", code: "CI", callSign: "+225" },
  { name: "Cameroon", code: "CM", callSign: "+237" },
  { name: "Congo (Kinshasa)", code: "CD", callSign: "+243" },
  { name: "Congo (Brazzaville)", code: "CG", callSign: "+242" },
  { name: "Cook Islands", code: "CK", callSign: "+682" },
  { name: "Colombia", code: "CO", callSign: "+57" },
  { name: "Comoros", code: "KM", callSign: "+269" },
  { name: "Cabo Verde", code: "CV", callSign: "+238" },
  { name: "Costa Rica", code: "CR", callSign: "+506" },
  { name: "Cuba", code: "CU", callSign: "+53" },
  { name: "Curaçao", code: "CW", callSign: "+599" },
  { name: "Christmas Island", code: "CX", callSign: "+61" },
  { name: "Czech Republic", code: "CZ", callSign: "+420" },
  { name: "Germany", code: "DE", callSign: "+49" },
  { name: "Djibouti", code: "DJ", callSign: "+253" },
  { name: "Dominica", code: "DM", callSign: "+1 767" },
  { name: "Denmark", code: "DK", callSign: "+45" },
  { name: "Dominican Republic", code: "DO", callSign: "+1 809" },
  { name: "Algeria", code: "DZ", callSign: "+213" },
  { name: "Ecuador", code: "EC", callSign: "+593" },
  { name: "Egypt", code: "EG", callSign: "+20" },
  { name: "Eritrea", code: "ER", callSign: "+291" },
  { name: "Western Sahara", code: "EH", callSign: "+212" },
  { name: "Spain", code: "ES", callSign: "+34" },
  { name: "Estonia", code: "EE", callSign: "+372" },
  { name: "Ethiopia", code: "ET", callSign: "+251" },
  { name: "Finland", code: "FI", callSign: "+358" },
  { name: "Fiji", code: "FJ", callSign: "+679" },
  { name: "Falkland Islands", code: "FK", callSign: "+500" },
  { name: "France", code: "FR", callSign: "+33" },
  { name: "Faroe Islands", code: "FO", callSign: "+298" },
  { name: "Micronesia", code: "FM", callSign: "+691" },
  { name: "Gabon", code: "GA", callSign: "+241" },
  { name: "United Kingdom", code: "GB", callSign: "+44" },
  { name: "Georgia", code: "GE", callSign: "+995" },
  { name: "Ghana", code: "GH", callSign: "+233" },
  { name: "Gibraltar", code: "GI", callSign: "+350" },
  { name: "Greenland", code: "GL", callSign: "+299" },
  { name: "Gambia", code: "GM", callSign: "+220" },
  { name: "Guinea", code: "GN", callSign: "+224" },
  { name: "Guadeloupe", code: "GP", callSign: "+590" },
  { name: "Equatorial Guinea", code: "GQ", callSign: "+240" },
  { name: "Greece", code: "GR", callSign: "+30" },
  { name: "Grenada", code: "GD", callSign: "+1 473" },
  { name: "Guatemala", code: "GT", callSign: "+502" },
  { name: "Guam", code: "GU", callSign: "+1 671" },
  { name: "Guinea-Bissau", code: "GW", callSign: "+245" },
  { name: "Guyana", code: "GY", callSign: "+592" },
  { name: "Hong Kong", code: "HK", callSign: "+852" },
  { name: "Heard Island and McDonald Islands", code: "HM", callSign: "+672" },
  { name: "Honduras", code: "HN", callSign: "+504" },
  { name: "Croatia", code: "HR", callSign: "+385" },
  { name: "Haiti", code: "HT", callSign: "+509" },
  { name: "Hungary", code: "HU", callSign: "+36" },
  { name: "Indonesia", code: "ID", callSign: "+62" },
  { name: "Ireland", code: "IE", callSign: "+353" },
  { name: "Israel", code: "IL", callSign: "+972" },
  { name: "India", code: "IN", callSign: "+91" },
  { name: "British Indian Ocean Territory", code: "IO", callSign: "+246" },
  { name: "Iraq", code: "IQ", callSign: "+964" },
  { name: "Iran", code: "IR", callSign: "+98" },
  { name: "Iceland", code: "IS", callSign: "+354" },
  { name: "Italy", code: "IT", callSign: "+39" },
  { name: "Jamaica", code: "JM", callSign: "+1 876" },
  { name: "Jordan", code: "JO", callSign: "+962" },
  { name: "Japan", code: "JP", callSign: "+81" },
  { name: "Kenya", code: "KE", callSign: "+254" },
  { name: "Kyrgyzstan", code: "KG", callSign: "+996" },
  { name: "Cambodia", code: "KH", callSign: "+855" },
  { name: "Kiribati", code: "KI", callSign: "+686" },
  { name: "Comoros", code: "KM", callSign: "+269" },
  { name: "Saint Kitts and Nevis", code: "KN", callSign: "+1 869" },
  { name: "North Korea", code: "KP", callSign: "+850" },
  { name: "South Korea", code: "KR", callSign: "+82" },
  { name: "Kuwait", code: "KW", callSign: "+965" },
  { name: "Kazakhstan", code: "KZ", callSign: "+7" },
  { name: "Lao People's Democratic Republic", code: "LA", callSign: "+856" },
  { name: "Lebanon", code: "LB", callSign: "+961" },
  { name: "Saint Lucia", code: "LC", callSign: "+1 758" },
  { name: "Liechtenstein", code: "LI", callSign: "+423" },
  { name: "Sri Lanka", code: "LK", callSign: "+94" },
  { name: "Liberia", code: "LR", callSign: "+231" },
  { name: "Lesotho", code: "LS", callSign: "+266" },
  { name: "Lithuania", code: "LT", callSign: "+370" },
  { name: "Luxembourg", code: "LU", callSign: "+352" },
  { name: "Latvia", code: "LV", callSign: "+371" },
  { name: "Libya", code: "LY", callSign: "+218" },
  { name: "Morocco", code: "MA", callSign: "+212" },
  { name: "Monaco", code: "MC", callSign: "+377" },
  { name: "Moldova", code: "MD", callSign: "+373" },
  { name: "Montenegro", code: "ME", callSign: "+382" },
  { name: "Madagascar", code: "MG", callSign: "+261" },
  { name: "Marshall Islands", code: "MH", callSign: "+692" },
  { name: "North Macedonia", code: "MK", callSign: "+389" },
  { name: "Mali", code: "ML", callSign: "+223" },
  { name: "Myanmar", code: "MM", callSign: "+95" },
  { name: "Mongolia", code: "MN", callSign: "+976" },
  { name: "Macao", code: "MO", callSign: "+853" },
  { name: "Mauritania", code: "MR", callSign: "+222" },
  { name: "Malta", code: "MT", callSign: "+356" },
  { name: "Mauritius", code: "MU", callSign: "+230" },
  { name: "Maldives", code: "MV", callSign: "+960" },
  { name: "Malawi", code: "MW", callSign: "+265" },
  { name: "Mexico", code: "MX", callSign: "+52" },
  { name: "Malaysia", code: "MY", callSign: "+60" },
  { name: "Mozambique", code: "MZ", callSign: "+258" },
  { name: "Namibia", code: "NA", callSign: "+264" },
  { name: "New Caledonia", code: "NC", callSign: "+687" },
  { name: "Niger", code: "NE", callSign: "+227" },
  { name: "Norfolk Island", code: "NF", callSign: "+672" },
  { name: "Nigeria", code: "NG", callSign: "+234" },
  { name: "Nicaragua", code: "NI", callSign: "+505" },
  { name: "Netherlands", code: "NL", callSign: "+31" },
  { name: "Norway", code: "NO", callSign: "+47" },
  { name: "Nepal", code: "NP", callSign: "+977" },
  { name: "Nauru", code: "NR", callSign: "+674" },
  { name: "New Zealand", code: "NZ", callSign: "+64" },
  { name: "Oman", code: "OM", callSign: "+968" },
  { name: "Pakistan", code: "PK", callSign: "+92" },
  { name: "Panama", code: "PA", callSign: "+507" },
  { name: "Peru", code: "PE", callSign: "+51" },
  { name: "Philippines", code: "PH", callSign: "+63" },
  { name: "Palestine", code: "PS", callSign: "+970" },
  { name: "Papua New Guinea", code: "PG", callSign: "+675" },
  { name: "Poland", code: "PL", callSign: "+48" },
  { name: "Portugal", code: "PT", callSign: "+351" },
  { name: "Paraguay", code: "PY", callSign: "+595" },
  { name: "Qatar", code: "QA", callSign: "+974" },
  { name: "Romania", code: "RO", callSign: "+40" },
  { name: "Russia", code: "RU", callSign: "+7" },
  { name: "Rwanda", code: "RW", callSign: "+250" },
  { name: "Saudi Arabia", code: "SA", callSign: "+966" },
  { name: "Sudan", code: "SD", callSign: "+249" },
  { name: "Senegal", code: "SN", callSign: "+221" },
  { name: "Singapore", code: "SG", callSign: "+65" },
  { name: "Slovenia", code: "SI", callSign: "+386" },
  { name: "Slovakia", code: "SK", callSign: "+421" },
  { name: "Sierra Leone", code: "SL", callSign: "+232" },
  { name: "San Marino", code: "SM", callSign: "+378" },
  { name: "Somalia", code: "SO", callSign: "+252" },
  { name: "Suriname", code: "SR", callSign: "+597" },
  { name: "South Sudan", code: "SS", callSign: "+211" },
  { name: "Sao Tome and Principe", code: "ST", callSign: "+239" },
  { name: "El Salvador", code: "SV", callSign: "+503" },
  { name: "Syria", code: "SY", callSign: "+963" },
  { name: "Swaziland", code: "SZ", callSign: "+268" },
  { name: "Chad", code: "TD", callSign: "+235" },
  { name: "Togo", code: "TG", callSign: "+228" },
  { name: "Thailand", code: "TH", callSign: "+66" },
  { name: "Tajikistan", code: "TJ", callSign: "+992" },
  { name: "Timor-Leste", code: "TL", callSign: "+670" },
  { name: "Turkmenistan", code: "TM", callSign: "+993" },
  { name: "Tunisia", code: "TN", callSign: "+216" },
  { name: "Tonga", code: "TO", callSign: "+676" },
  { name: "Turkey", code: "TR", callSign: "+90" },
  { name: "Trinidad and Tobago", code: "TT", callSign: "+1 868" },
  { name: "Tuvalu", code: "TV", callSign: "+688" },
  { name: "Taiwan", code: "TW", callSign: "+886" },
  { name: "Tanzania", code: "TZ", callSign: "+255" },
  { name: "Uganda", code: "UG", callSign: "+256" },
  { name: "Ukraine", code: "UA", callSign: "+380" },
  { name: "Uruguay", code: "UY", callSign: "+598" },
  { name: "United States", code: "US", callSign: "+1" },
  { name: "Uzbekistan", code: "UZ", callSign: "+998" },
  { name: "Vatican City", code: "VA", callSign: "+379" },
  { name: "Saint Vincent and the Grenadines", code: "VC", callSign: "+1 784" },
  { name: "Venezuela", code: "VE", callSign: "+58" },
  { name: "Virgin Islands (British)", code: "VG", callSign: "+1 284" },
  { name: "Virgin Islands (U.S.)", code: "VI", callSign: "+1 340" },
  { name: "Vietnam", code: "VN", callSign: "+84" },
  { name: "Vanuatu", code: "VU", callSign: "+678" },
  { name: "Samoa", code: "WS", callSign: "+685" },
  { name: "Yemen", code: "YE", callSign: "+967" },
  { name: "South Africa", code: "ZA", callSign: "+27" },
  { name: "Zambia", code: "ZM", callSign: "+260" },
  { name: "Zimbabwe", code: "ZW", callSign: "+263" }
];