// countries.ts
export const countries = [
  { name: "Aruba", code: "AW" },
  { name: "Afghanistan", code: "AF" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Andorra", code: "AD" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "American Samoa", code: "AS" },
  { name: "Antarctica", code: "AQ" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Burundi", code: "BI" },
  { name: "Belgium", code: "BE" },
  { name: "Benin", code: "BJ" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Bangladesh", code: "BD" },
  { name: "Bulgaria", code: "BG" },
  { name: "Bahrain", code: "BH" },
  { name: "Bahamas", code: "BS" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Saint Barthélemy", code: "BL" },
  { name: "Belarus", code: "BY" },
  { name: "Belize", code: "BZ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bolivia", code: "BO" },
  { name: "Brazil", code: "BR" },
  { name: "Barbados", code: "BB" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bhutan", code: "BT" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Botswana", code: "BW" },
  { name: "Central African Republic", code: "CF" },
  { name: "Canada", code: "CA" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Switzerland", code: "CH" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Côte d'Ivoire", code: "CI" },
  { name: "Cameroon", code: "CM" },
  { name: "Congo (Kinshasa)", code: "CD" },
  { name: "Congo (Brazzaville)", code: "CG" },
  { name: "Cook Islands", code: "CK" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cuba", code: "CU" },
  { name: "Curaçao", code: "CW" },
  { name: "Christmas Island", code: "CX" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Germany", code: "DE" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Denmark", code: "DK" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Algeria", code: "DZ" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "Eritrea", code: "ER" },
  { name: "Western Sahara", code: "EH" },
  { name: "Spain", code: "ES" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Finland", code: "FI" },
  { name: "Fiji", code: "FJ" },
  { name: "Falkland Islands", code: "FK" },
  { name: "France", code: "FR" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Micronesia", code: "FM" },
  { name: "Gabon", code: "GA" },
  { name: "United Kingdom", code: "GB" },
  { name: "Georgia", code: "GE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greenland", code: "GL" },
  { name: "Gambia", code: "GM" },
  { name: "Guinea", code: "GN" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guam", code: "GU" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Hong Kong", code: "HK" },
  { name: "Heard Island and McDonald Islands", code: "HM" },
  { name: "Honduras", code: "HN" },
  { name: "Croatia", code: "HR" },
  { name: "Haiti", code: "HT" },
  { name: "Hungary", code: "HU" },
  { name: "Indonesia", code: "ID" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "India", code: "IN" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Iraq", code: "IQ" },
  { name: "Iran", code: "IR" },
  { name: "Iceland", code: "IS" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Jordan", code: "JO" },
  { name: "Japan", code: "JP" },
  { name: "Kenya", code: "KE" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Cambodia", code: "KH" },
  { name: "Kiribati", code: "KI" },
  { name: "Comoros", code: "KM" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "North Korea", code: "KP" },
  { name: "South Korea", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Lao People's Democratic Republic", code: "LA" },
  { name: "Lebanon", code: "LB" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Liberia", code: "LR" },
  { name: "Lesotho", code: "LS" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Latvia", code: "LV" },
  { name: "Libya", code: "LY" },
  { name: "Morocco", code: "MA" },
  { name: "Monaco", code: "MC" },
  { name: "Moldova", code: "MD" },
  { name: "Montenegro", code: "ME" },
  { name: "Madagascar", code: "MG" },
  { name: "Marshall Islands", code: "MH" },
  { name: "North Macedonia", code: "MK" },
  { name: "Mali", code: "ML" },
  { name: "Myanmar", code: "MM" },
  { name: "Mongolia", code: "MN" },
  { name: "Macao", code: "MO" },
  { name: "Mauritania", code: "MR" },
  { name: "Malta", code: "MT" },
  { name: "Mauritius", code: "MU" },
  { name: "Maldives", code: "MV" },
  { name: "Malawi", code: "MW" },
  { name: "Mexico", code: "MX" },
  { name: "Malaysia", code: "MY" },
  { name: "Mozambique", code: "MZ" },
  { name: "Namibia", code: "NA" },
  { name: "New Caledonia", code: "NC" },
  { name: "Niger", code: "NE" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Nigeria", code: "NG" },
  { name: "Nicaragua", code: "NI" },
  { name: "Netherlands", code: "NL" },
  { name: "Norway", code: "NO" },
  { name: "Nepal", code: "NP" },
  { name: "Nauru", code: "NR" },
  { name: "New Zealand", code: "NZ" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Panama", code: "PA" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Palestine", code: "PS" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Paraguay", code: "PY" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Sudan", code: "SD" },
  { name: "Senegal", code: "SN" },
  { name: "Singapore", code: "SG" },
  { name: "Slovenia", code: "SI" },
  { name: "Slovakia", code: "SK" },
  { name: "Sierra Leone", code: "SL" },
  { name: "San Marino", code: "SM" },
  { name: "Somalia", code: "SO" },
  { name: "Suriname", code: "SR" },
  { name: "South Sudan", code: "SS" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "El Salvador", code: "SV" },
  { name: "Syria", code: "SY" },
  { name: "Swaziland", code: "SZ" },
  { name: "Chad", code: "TD" },
  { name: "Togo", code: "TG" },
  { name: "Thailand", code: "TH" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tunisia", code: "TN" },
  { name: "Tonga", code: "TO" },
  { name: "Turkey", code: "TR" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Taiwan", code: "TW" },
  { name: "Tanzania", code: "TZ" },
  { name: "Ukraine", code: "UA" },
  { name: "Uganda", code: "UG" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vatican City", code: "VA" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Vanuatu", code: "VU" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Samoa", code: "WS" },
  { name: "Yemen", code: "YE" },
  { name: "Mayotte", code: "YT" },
  { name: "South Africa", code: "ZA" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" }
];
